name: smart_school
description: "Smart School IoT mobile app for monitoring and controlling smart school environment."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  supabase_flutter: ^2.3.1
  fl_chart: ^0.66.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  web_socket_channel: ^2.4.0
  camera: ^0.10.5+9
  video_player: ^2.6.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
